application: giladfoyer
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:


- url: /static
  static_dir: static
  
- url: /.*
  script: giladfoyer.app

libraries:
- name: webapp2
  version: latest